// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOEJkZSA-zeBwSdyPs8zh-kkxdz_wfeW4',
    appId: '1:1054380508990:web:47b18ad81977b5debcce6f',
    messagingSenderId: '1054380508990',
    projectId: 'flutcam',
    authDomain: 'flutcam.firebaseapp.com',
    storageBucket: 'flutcam.appspot.com',
    measurementId: 'G-404NBS3D3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1k7WqMUHOIe7nEu7n78wAWT4ENfnVh1w',
    appId: '1:1054380508990:android:3633dcface09b6f2bcce6f',
    messagingSenderId: '1054380508990',
    projectId: 'flutcam',
    storageBucket: 'flutcam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKSSWrE6swNwWvMz5I0Y5R2gSQZUW05Q',
    appId: '1:1054380508990:ios:7bac83a32d06aeb4bcce6f',
    messagingSenderId: '1054380508990',
    projectId: 'flutcam',
    storageBucket: 'flutcam.appspot.com',
    iosClientId:
        '1054380508990-cl30d9ljeidl8pp5u5kv8ot3if3pit8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKSSWrE6swNwWvMz5I0Y5R2gSQZUW05Q',
    appId: '1:1054380508990:ios:7bac83a32d06aeb4bcce6f',
    messagingSenderId: '1054380508990',
    projectId: 'flutcam',
    storageBucket: 'flutcam.appspot.com',
    iosClientId:
        '1054380508990-cl30d9ljeidl8pp5u5kv8ot3if3pit8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCam',
  );
}
